### ISSUE TITLE
Calipso breaks with hooks-js >=0.4

### ISSUE THREAD

**Issue by tomerlichtash** [bnoguchi/hooks-js#1]
```
npm info fetch http://registry.npmjs.org/hooks/-/hooks-0.1.9.tgz
npm info calculating sha1 /var/folders/L5/L5b8zccxFYiv8aXPH4Xpr++++TI/-Tmp-/npm-1311158342434/1311158345082-0.03321287292055786/tmp.tgz
npm info shasum 064e8bba3fca0e6611408c011ba7958c1055bb4e
npm ERR! Error: Using '>=' with 0.4.x makes no sense. Don't do it.
npm ERR!     at /usr/local/Cellar/npm/0.2.11-5/libexec/lib/utils/semver.js:94:29
npm ERR!     at String.replace (native)
npm ERR!     at replaceXRange (/usr/local/Cellar/npm/0.2.11-5/libexec/lib/utils/semver.js:88:25)
npm ERR!     at Array.map (native)
npm ERR!     at replaceXRanges (/usr/local/Cellar/npm/0.2.11-5/libexec/lib/utils/semver.js:84:17)
npm ERR!     at Array.map (native)
npm ERR!     at toComparators (/usr/local/Cellar/npm/0.2.11-5/libexec/lib/utils/semver.js:66:8)
npm ERR!     at Object.validRange (/usr/local/Cellar/npm/0.2.11-5/libexec/lib/utils/semver.js:138:11)
npm ERR!     at testEngine (/usr/local/Cellar/npm/0.2.11-5/libexec/lib/utils/read-json.js:218:44)
npm ERR!     at /usr/local/Cellar/npm/0.2.11-5/libexec/lib/utils/read-json.js:159:10
npm ERR! Report this *entire* log at 
npm ERR! or email it to 
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm info range timespan@2.x.x
npm not ok
```

Previously: http://stackoverflow.com/questions/6760622/failed-installation-of-calipso-under-nodejs

**Comment by bnoguchi** [comment]
Updated package.json. Try npm installing it again.

**Comment by tomerlichtash** [comment]
that was _fast_. tnx.
